os: linux
language: python
python: "3.6"
dist: focal
compiler:
    - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get upgrade -y
  - sudo apt-get install -y --no-install-recommends binutils ca-certificates curl less gdb htop iperf3 iputils-ping iproute2 jq libaio1 libnuma1 libpython2.7 libstdc++6 libunwind8 libncurses5 mdadm net-tools netbase netcat nvme-cli pciutils python3 sysstat tcpdump tmux tzdata vim wget 

install:
# Install conan
  - pip install conan
  - conan remote add ebay-local $CONAN_ARTIFACTORY_URL

# Automatic detection of your arch, compiler, etc.
  - conan user

script:
# Download dependencies and build project
  - conan install .
