name: Check Modified File

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if file is modified
        run: |
          if [[ $(git diff --name-only ${{ github.base_ref }}..${{ github.sha }}) == *conanfile.py* ]]; then
            echo "File is modified"
          else
            echo "File is not modified"
          fi
